CREATE TABLE zwierzeta
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Imie VARCHAR(45) NOT NULL,
  Nazwa VARCHAR(30) NOT NULL,
  Rodzaj VARCHAR(20) NOT NULL,
  Wybieg VARCHAR(30) NOT NULL,
  Wiek INT,
  Plec VARCHAR(15)
);

CREATE TABLE wybieg
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Rodzaj VARCHAR(20) NOT NULL,
  Klatka VARCHAR(3) NOT NULL,
  Ilosc_miejsc INT NOT NULL,
  Strefa INT NOT NULL
);

CREATE TABLE strefa
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR(45) NOT NULL,
  Ilosc_wybiegow INT NOT NULL,
  Magazyn INT NOT NULL
);

CREATE TABLE pokarm
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Nazwa VARCHAR(45),
  Rodzaj VARCHAR(45),
  Magazyn INT NOT NULL,
  Ilosc INT NOT NULL
);

CREATE TABLE magazyn
(
  Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Strefa INT NOT NULL,
  Pojemnosc INT NOT NULL,
  chlodzenie VARCHAR(3) NOT NULL
);